/**:
  ros__parameters:
    use_sim_time: true
    global_frame: odom
    robot_base_frame: base_link
    rolling_window: true
    width: 20
    height: 20
    resolution: 0.1
    footprint: "[[0.25, 0.25], [0.25, -0.25], [-0.25, -0.25], [-0.25, 0.25]]"
    plugins: ["obstacle_layer", "inflation_layer"]

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: depth_cloud
      depth_cloud:
        topic: /camera/points
        data_type: PointCloud2
        marking: true
        clearing: true
        obstacle_range: 6.0
        raytrace_range: 8.0
        min_obstacle_height: 0.1
        max_obstacle_height: 3.0

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.5
