drones:
  drone1:
    target_system: 2
    prefix: '/px4_1'
  drone2:
    target_system: 3
    prefix: '/px4_2'

ble_beacons: 
  beacon1:
    name: '1'
    position: [0.0, 0.0, 0.0]
  beacon2:
    name: '2'
    position: [2.0, 2.0, 0.0]
  beacon3:
    name: '3'
    position: [3.0, 3.0, 0.0]
  beacon4:
    name: '4'
    position: [1.0, 1.0, 0.0]

rssi_settings:
  rssi0: -50.0
  path_loss_n: 2.5